# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern *dev.yaml,
  # KMS set A is used
  # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
  - path_regex: '.*-secrets\.yaml$'
    age: age1tpgmq2ljku6gkedc3w35zz9vxshcu6mhv6qphr5z88eqns0yzafscseppw
