apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- else }}
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
    type: local
    app: {{ .Values.labels.app }}
    group: {{ .Values.labels.group }}
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi